---
micronaut:
  application:
    name: mn-docker-env-test

---
micronaut:
    router:
        static-resources:
            swagger:
                paths:
                - classpath:META-INF/swagger
                - classpath:swagger
                mapping: /swagger/**

---
micronaut:
  io:
    watch:
      paths: src/main
      restart: true
